Repository ProntoPro/create-react-app, pull requests merged in 2019-07, with the labels that each got.

#1 First draft of prontopro scripts
  packages/react-scripts/config/env.js
  packages/react-scripts/config/paths.js
  packages/react-scripts/config/prontopro/nativeNullLoader.js
  packages/react-scripts/config/prontopro/setEnvironmentLoader.js
  packages/react-scripts/config/prontopro/stripE2ETargetsLoader.js
  packages/react-scripts/config/prontopro/utils/index.js
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
  packages/react-scripts/package.json
  packages/react-scripts/scripts/start.js
Labels: area/TECH, area/WEB, kind/ENHANCEMENT, status/OK-TO-MERGE, tribe/GROWTH :chart_with_upwards_trend:

#8 [TECH] #4: throw if no environment is set
  packages/react-scripts/config/paths.js
Labels: area/TECH, kind/ENHANCEMENT, status/OK-TO-MERGE, tribe/GROWTH :chart_with_upwards_trend:

#7 [TECH]: make JS injection configurable in development
  packages/react-scripts/config/webpack.config.dev.js
  packages/react-scripts/config/webpack.config.prod.js
Labels: area/TECH, kind/ENHANCEMENT, status/OK-TO-MERGE, tribe/GROWTH :chart_with_upwards_trend:

#9 [TECH]: bump v2 version
  packages/react-scripts/package.json
Labels: area/TECH, kind/RELEASE, status/OK-TO-MERGE, tribe/GROWTH :chart_with_upwards_trend:

#11 refs #10: Move PP_ENVIRONMENT check in env.js
  packages/react-scripts/config/env.js
  packages/react-scripts/config/paths.js
  packages/react-scripts/package.json
Labels: area/TECH, area/WEB, kind/ENHANCEMENT, status/OK-TO-MERGE, tribe/GROWTH :chart_with_upwards_trend:
